## **Install Required Libraries**

In [1]:
!pip install nltk
!pip install spacy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2022.10.31)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.65.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: spacy in /usr/local/lib/python3.10/dist-packages (3.5.2)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.10/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (1.0.4)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (1.0.9)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy) (2.0.7)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.10/dist-packages (from spacy) (3.0.8)
Requirement already satisfied: thinc<8.2.0,>=8.1.8 in /usr/local/lib/python3.10/dist-packages (from spacy) (8.1.9)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from spacy) (1.1.1)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.10/dist-packages (from spacy) (2.4.6)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.10/dist-packages (from spacy) (2.0.8)
Requirement already satisfied: typer<0.8.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (0.7.0)
Requirement already satisfied: pathy>=0.10.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (0.10.1)
Requirement already satisfied: smart-open<7.0.0,>=5.2.1 in /usr/local/lib/python3.10/dist-packages (from spacy) (6.3.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (4.65.0)
Requirement already satisfied: numpy>=1.15.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (1.22.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (2.27.1)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4 in /usr/local/lib/python3.10/dist-packages (from spacy) (1.10.7)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from spacy) (3.1.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from spacy) (67.7.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (23.1)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in /usr/local/lib/python3.10/dist-packages (from spacy) (3.3.0)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from pydantic!=1.8,!=1.8.1,<1.11.0,>=1.7.4->spacy) (4.5.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in /usr/local/lib/python3.10/dist-packages (from thinc<8.2.0,>=8.1.8->spacy) (0.7.9)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.10/dist-packages (from thinc<8.2.0,>=8.1.8->spacy) (0.0.4)
Requirement already satisfied: click<9.0.0,>=7.1.1 in /usr/local/lib/python3.10/dist-packages (from typer<0.8.0,>=0.3.0->spacy) (8.1.3)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->spacy) (2.1.2)

## **Import Libraries**

In [2]:
import pandas as pd
import numpy as np
import re
import nltk
import spacy
import string

In [3]:
data=pd.read_csv("/content/1429_1.csv")
data.head(10)

<ipython-input-3-00295c2335b1>:1: DtypeWarning: Columns (1,10) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv("/content/1429_1.csv")

,id,name,asins,brand,categories,keys,manufacturer,reviews.date,reviews.dateAdded,reviews.dateSeen,...,reviews.doRecommend,reviews.id,reviews.numHelpful,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username
0,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,This product so far has not disappointed. My c...,Kindle,NaN,NaN,Adapter
1,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,great for beginner or experienced person. Boug...,very fast,NaN,NaN,truman
2,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,Inexpensive tablet for him to use and learn on...,Beginner tablet for our 9 year old son.,NaN,NaN,DaveZ
3,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-13T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,4.0,http://reviews.bestbuy.com/3545/5620406/review...,I've had my Fire HD 8 two weeks now and I love...,Good!!!,NaN,NaN,Shacks
4,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-12T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,I bought this for my grand daughter when she c...,Fantastic Tablet for kids,NaN,NaN,explore42
5,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-12T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,This amazon fire 8 inch tablet is the perfect ...,Just what we expected,NaN,NaN,tklit
6,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-12T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,4.0,http://reviews.bestbuy.com/3545/5620406/review...,"Great for e-reading on the go, nice and light ...",great e-reader tablet,NaN,NaN,Droi
7,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-12T00:00:00.000Z,2017-07-03T23:33:15Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,"I gave this as a Christmas gift to my inlaws, ...",Great for gifts,NaN,NaN,Kacy
8,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-23T00:00:00.000Z,2017-07-03T23:28:24Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:44:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,Great as a device to read books. I like that i...,Great for reading,NaN,NaN,Weebee
9,AVqkIhwDv8e3D1O-lebb,"All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...",B01AHB9CN2,Amazon,"Electronics,iPad & Tablets,All Tablets,Fire Ta...","841667104676,amazon/53004484,amazon/b01ahb9cn2...",Amazon,2017-01-23T00:00:00.000Z,2017-07-03T23:28:24Z,"2017-06-07T09:04:00.000Z,2017-04-30T00:44:00.000Z",...,True,NaN,0.0,5.0,http://reviews.bestbuy.com/3545/5620406/review...,I love ordering books and reading them with th...,Great and lightweight reader,NaN,NaN,RoboBob

In [4]:
data.shape

(34660, 21)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34660 entries, 0 to 34659
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    34660 non-null  object
 1   name                  27900 non-null  object
 2   asins                 34658 non-null  object
 3   brand                 34660 non-null  object
 4   categories            34660 non-null  object
 5   keys                  34660 non-null  object
 6   manufacturer          34660 non-null  object
 7   reviews.date          34621 non-null  object
 8   reviews.dateAdded     24039 non-null  object
 9   reviews.dateSeen      34660 non-null  object
 10  reviews.didPurchase   1 non-null      object
 11  reviews.doRecommend   34066 non-null  object
 12  reviews.id            1 non-null      float64
 13  reviews.numHelpful    34131 non-null  float64
 14  reviews.rating        34627 non-null  float64
 15  reviews.sourceURLs    34660 non-null  object
 16  reviews.text          34659 non-null  object
 17  reviews.title         34655 non-null  object
 18  reviews.userCity      0 non-null      float64
 19  reviews.userProvince  0 non-null      float64
 20  reviews.username      34658 non-null  object
dtypes: float64(5), object(16)
memory usage: 5.6+ MB

In [6]:
df=data[['reviews.title','reviews.text',]]
df=df.astype(str)
df.head()

,reviews.title,reviews.text
0,Kindle,This product so far has not disappointed. My c...
1,very fast,great for beginner or experienced person. Boug...
2,Beginner tablet for our 9 year old son.,Inexpensive tablet for him to use and learn on...
3,Good!!!,I've had my Fire HD 8 two weeks now and I love...
4,Fantastic Tablet for kids,I bought this for my grand daughter when she c...

In [7]:
DF=df.copy()

## **Removal of Punctuations:**

In [8]:
PUNCH_TO_REMOVE=string.punctuation
def remove_punctuation(text):
  return text.translate(str.maketrans('','',PUNCH_TO_REMOVE))

df[['reviews.title','reviews.text']]=df[['reviews.title','reviews.text']].applymap(lambda text:remove_punctuation(text))
df.head()

,reviews.title,reviews.text
0,Kindle,This product so far has not disappointed My ch...
1,very fast,great for beginner or experienced person Bough...
2,Beginner tablet for our 9 year old son,Inexpensive tablet for him to use and learn on...
3,Good,Ive had my Fire HD 8 two weeks now and I love ...
4,Fantastic Tablet for kids,I bought this for my grand daughter when she c...

## **Removal of stopwords:**

In [9]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [10]:
from nltk.corpus import stopwords
",".join(stopwords.words("english"))

"i,me,my,myself,we,our,ours,ourselves,you,you're,you've,you'll,you'd,your,yours,yourself,yourselves,he,him,his,himself,she,she's,her,hers,herself,it,it's,its,itself,they,them,their,theirs,themselves,what,which,who,whom,this,that,that'll,these,those,am,is,are,was,were,be,been,being,have,has,had,having,do,does,did,doing,a,an,the,and,but,if,or,because,as,until,while,of,at,by,for,with,about,against,between,into,through,during,before,after,above,below,to,from,up,down,in,out,on,off,over,under,again,further,then,once,here,there,when,where,why,how,all,any,both,each,few,more,most,other,some,such,no,nor,not,only,own,same,so,than,too,very,s,t,can,will,just,don,don't,should,should've,now,d,ll,m,o,re,ve,y,ain,aren,aren't,couldn,couldn't,didn,didn't,doesn,doesn't,hadn,hadn't,hasn,hasn't,haven,haven't,isn,isn't,ma,mightn,mightn't,mustn,mustn't,needn,needn't,shan,shan't,shouldn,shouldn't,wasn,wasn't,weren,weren't,won,won't,wouldn,wouldn't"

In [11]:
STOP_WORDS=set(stopwords.words("english"))
def remove_stopwords(text):
  return " ".join([word for word in str(text).split() if word not in STOP_WORDS])

df[['reviews.title','reviews.text']]=df[['reviews.title','reviews.text']].applymap(lambda text:remove_stopwords(text))
df.head()

,reviews.title,reviews.text
0,Kindle,This product far disappointed My children love...
1,fast,great beginner experienced person Bought gift ...
2,Beginner tablet 9 year old son,Inexpensive tablet use learn step NABI He thri...
3,Good,Ive Fire HD 8 two weeks I love This tablet gre...
4,Fantastic Tablet kids,I bought grand daughter comes visit I set user...

## **Stemming**

In [12]:
from nltk.stem.porter import PorterStemmer
stemmer=PorterStemmer()
def stem_words(text):
  return " ".join([stemmer.stem(word) for word in text.split()])

df[['reviews.title_stemmed','reviews.text_stemmed']]=df[['reviews.title','reviews.text']].applymap(lambda text:stem_words(text))
df.head()

,reviews.title,reviews.text,reviews.title_stemmed,reviews.text_stemmed
0,Kindle,This product far disappointed My children love...,kindl,thi product far disappoint my children love us...
1,fast,great beginner experienced person Bought gift ...,fast,great beginn experienc person bought gift love
2,Beginner tablet 9 year old son,Inexpensive tablet use learn step NABI He thri...,beginn tablet 9 year old son,inexpens tablet use learn step nabi he thrill ...
3,Good,Ive Fire HD 8 two weeks I love This tablet gre...,good,ive fire hd 8 two week i love thi tablet great...
4,Fantastic Tablet kids,I bought grand daughter comes visit I set user...,fantast tablet kid,i bought grand daughter come visit i set user ...

## **Lemmatization**

In [13]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [14]:
from nltk.stem import WordNetLemmatizer

lemmatizer=WordNetLemmatizer()
def lemmatize_words(text):
  return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

df[['reviews.title_lemmatized','reviews.text_lemmatized']]=df[['reviews.title','reviews.text']].applymap(lambda text:lemmatize_words(text))
df.head()

,reviews.title,reviews.text,reviews.title_stemmed,reviews.text_stemmed,reviews.title_lemmatized,reviews.text_lemmatized
0,Kindle,This product far disappointed My children love...,kindl,thi product far disappoint my children love us...,Kindle,This product far disappointed My child love us...
1,fast,great beginner experienced person Bought gift ...,fast,great beginn experienc person bought gift love,fast,great beginner experienced person Bought gift ...
2,Beginner tablet 9 year old son,Inexpensive tablet use learn step NABI He thri...,beginn tablet 9 year old son,inexpens tablet use learn step nabi he thrill ...,Beginner tablet 9 year old son,Inexpensive tablet use learn step NABI He thri...
3,Good,Ive Fire HD 8 two weeks I love This tablet gre...,good,ive fire hd 8 two week i love thi tablet great...,Good,Ive Fire HD 8 two week I love This tablet grea...
4,Fantastic Tablet kids,I bought grand daughter comes visit I set user...,fantast tablet kid,i bought grand daughter come visit i set user ...,Fantastic Tablet kid,I bought grand daughter come visit I set user ...

In [15]:
df=df[["reviews.title","reviews.title_stemmed","reviews.title_lemmatized","reviews.text","reviews.text_stemmed","reviews.text_lemmatized"]]
df.head(10)

,reviews.title,reviews.title_stemmed,reviews.title_lemmatized,reviews.text,reviews.text_stemmed,reviews.text_lemmatized
0,Kindle,kindl,Kindle,This product far disappointed My children love...,thi product far disappoint my children love us...,This product far disappointed My child love us...
1,fast,fast,fast,great beginner experienced person Bought gift ...,great beginn experienc person bought gift love,great beginner experienced person Bought gift ...
2,Beginner tablet 9 year old son,beginn tablet 9 year old son,Beginner tablet 9 year old son,Inexpensive tablet use learn step NABI He thri...,inexpens tablet use learn step nabi he thrill ...,Inexpensive tablet use learn step NABI He thri...
3,Good,good,Good,Ive Fire HD 8 two weeks I love This tablet gre...,ive fire hd 8 two week i love thi tablet great...,Ive Fire HD 8 two week I love This tablet grea...
4,Fantastic Tablet kids,fantast tablet kid,Fantastic Tablet kid,I bought grand daughter comes visit I set user...,i bought grand daughter come visit i set user ...,I bought grand daughter come visit I set user ...
5,Just expected,just expect,Just expected,This amazon fire 8 inch tablet perfect size I ...,thi amazon fire 8 inch tablet perfect size i p...,This amazon fire 8 inch tablet perfect size I ...
6,great ereader tablet,great eread tablet,great ereader tablet,Great ereading go nice light weight price poin...,great eread go nice light weight price point g...,Great ereading go nice light weight price poin...
7,Great gifts,great gift,Great gift,I gave Christmas gift inlaws husband uncle The...,i gave christma gift inlaw husband uncl they l...,I gave Christmas gift inlaws husband uncle The...
8,Great reading,great read,Great reading,Great device read books I like links borrowed ...,great devic read book i like link borrow libra...,Great device read book I like link borrowed li...
9,Great lightweight reader,great lightweight reader,Great lightweight reader,I love ordering books reading reader,i love order book read reader,I love ordering book reading reader